events {}

http {
    server {
        listen 443 ssl;
        server_name apigateway-dev;

        ssl_certificate     /etc/nginx/certs/apigateway-cert.pem;
        ssl_certificate_key /etc/nginx/certs/apigateway-key.pem;
        ssl_client_certificate /etc/nginx/certs/ca-cert.pem;
        ssl_verify_client on;

        location / {
            proxy_pass http://apigateway-dev:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
        }
    }
}