server {
    listen 443 ssl;
    server_name api-gateway-dev;

    ssl_certificate /etc/ssl/certs/nginx-apigateway-dev-cert.pem;
    ssl_certificate_key /etc/ssl/keys/nginx-apigateway-dev-key.pem;
    ssl_client_certificate /etc/ssl/certs/ca-cert.pem;
    ssl_verify_client on;

    # Forward the root / to the landing service
    location / {
        proxy_pass http://landing-dev:8088/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Forward request /api/* to the api gateway
    location /api/ {
        proxy_pass http://apigateway-dev:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}