###############################################
# GESTIONE VARIABILI D'AMBIENTE (BACKEND E FRONTEND)
#
# Tutte le variabili di configurazione (backend e frontend, incluse le porte) sono centralizzate nei file:
#   .env.dev  (per sviluppo, in questa stessa cartella)
#   .env.prod (per produzione, in questa stessa cartella)
#
# Modifica questi file per cambiare le porte o le variabili di backend e frontend.
# I docker-compose usano solo questi file come env_file per tutti i servizi.
###############################################
services:
  # Nome progetto/stack per i container
  # Per ambiente PROD: ecommerce-builder-prod
  # (Impostato tramite "name" o "-p" da CLI, oppure con "COMPOSE_PROJECT_NAME" nel file .env)
  backend-prod:
    build:
      context: ../../ecommerce-builder-backend
      dockerfile: Dockerfile-prod
    container_name: ${PROJECT_NAME}-backend-prod
    env_file:
      - .env
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    ports:
      - "${BACKEND_PORT_SOURCE}:${BACKEND_PORT_TARGET}"
    volumes:
      - ../../ecommerce-builder-backend:/app
      - ../../ecommerce-builder-backend/media:/app/media
    command: >
      sh -c "python manage.py collectstatic --noinput && \
             python manage.py runserver 0.0.0.0:${BACKEND_PORT_TARGET}"
    depends_on:
      - db-prod

  frontend-prod:
    build:
      context: ../../ecommerce-builder-frontend/frontend
      dockerfile: Dockerfile-prod
    container_name: ${PROJECT_NAME}-frontend-prod
    env_file:
      - .env
    environment:
      VITE_TEST_ENV: ${VITE_TEST_ENV}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      VITE_PROJECT_NAME: ${VITE_PROJECT_NAME}
      FRONTEND_PORT_TARGET: ${FRONTEND_PORT_TARGET}
    ports:
      - "${FRONTEND_PORT_SOURCE}:${FRONTEND_PORT_TARGET}"
    volumes:
      - ../../ecommerce-builder-frontend/frontend:/app
      - /app/node_modules
    depends_on:
      - backend-prod

  db-prod:
    image: postgres:16-alpine
    container_name: ${PROJECT_NAME}-db-prod
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT_TARGET: ${DB_PORT_TARGET}
    ports:
      - "${DB_PORT_SOURCE}:${DB_PORT_TARGET}"
    volumes:
      - pgdata-prod:/var/lib/postgresql/data


volumes:
  pgdata-prod:
