server {
    listen 443 ssl;
    server_name apigateway-prod;

    ssl_certificate     /etc/nginx/certs/apigateway-cert.pem;
    ssl_certificate_key /etc/nginx/certs/apigateway-key.pem;
    ssl_client_certificate /etc/nginx/certs/ca-cert.pem;
    ssl_verify_client on;

    location / {
        proxy_pass https://apigateway-prod:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
}